version: "3"

tasks:
  generate:
    aliases:
      - api
    desc: "Generate Go code from proto files"
    cmds:
      - protoc -I proto proto/payment_service.proto --go_out=./pkg/api/ --go_opt=paths=source_relative --go-grpc_out=./pkg/api/ --go-grpc_opt=paths=source_relative
  test:
    desc: "testing payment_service"
    cmds:
      - go test ./internal/service
      - go test ./internal/handler
      - go test ./internal/data
