services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: PASSWORD

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

volumes:
  minio_data:


