services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres      # Должно совпадать с POSTGRES_USER в коде
      POSTGRES_PASSWORD: postgres  # Должно совпадать с POSTGRES_PASSWORD в коде
      POSTGRES_DB: studyflow       # Должно совпадать с POSTGRES_DB в коде
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  
